#
# APPLICATION CONFIG DEV
#

app:
  bitpanda:
    apikey:

spring:
  datasource:
    initialization-mode: always
    password: <PASSWORD>
    url: jdbc:mysql://<SERVER>[:HOST]/<DATABASE>?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: <USERNAME>
  jpa:
    hibernate:
      ddl-auto: create
  main:
    banner-mode: "off"
